# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  url = "#about"
  weight = 10

[[main]]
  name = "Posts"
  url = "/post/"
  weight = 20

[[main]]
  name = "Projects"
  url = "/project/"
  weight = 30

[[main]]
  name = "Publications"
  identifier = "publications"
  url = "/publication/"
  weight = 40
  
[[main]]
 name = "thesis"
 parent = "publications"
 url = "/publication/thesis/"
 weight = 44

[[main]]
 name = "journal articles"
 parent = "publications"
 url = "/publication/journal-articles/"
 weight = 41
 
 [[main]]
 name = "conference abstracts"
 parent = "publications"
 url = "/publication/conference-abstract/"
 weight = 42

[[main]]
  name = "Tutorials"
  url = "/tutorial/"
  weight = 50
  
[[main]]
  name = "Teaching"
  url = "#teaching"
  weight = 55


[[main]]
  name = "Contact"
  url = "#contact"
  weight = 60

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
